---
- name: Install UFW
  apt:
    name: ufw
    state: present

- name: Allow SSH
  ufw:
    rule: allow
    port: '22'
    state: enabled

- name: Allow required ports
  ufw:
    rule: allow
    port: "{{ item }}"
    state: enabled
  loop: "{{ firewall_allowed_ports }}"

- name: Enable UFW
  ufw:
    state: enabled