- name: Configure DevOps platform infrastructure
  hosts: all
  become: yes
  vars_files:
    - group_vars/all.yml

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    - name: Install essential packages
      apt:
        name:
          - curl
          - wget
          - git
          - htop
          - tree
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Docker
      include_role:
        name: docker
      tags: docker

    - name: Install Kubernetes tools
      include_role:
        name: kubernetes
      tags: k8s

    - name: Configure firewall
      include_role:
        name: firewall
      tags: firewall